#!/bin/bash
LIST="rpi01 rpitest rpi02 rpi03 rpi04 rpi05 rpi06 rpi07 rpi08 rpi09 rpi10 rpi11 rpi12 rpi13 rpi14 rpi15 rpi16 rpi17 rpi18 rpi19 rpi20"

for a in $LIST;
do 
	ping $a -c 1 -W 1 &>/dev/null
if [ $? -eq 0 ] ; then
	echo [$a] ": alive"
else
	echo [$a] ": not alive"
fi

done

